// P7-M017 — Gateway drain verification under CONTAINER conditions.
//
// Manual release-verification script (NOT a unit test): opens N REAL
// authenticated WebSocket sessions against a gateway running in the
// release container, keeps them open with pending durable writes, then
// `docker stop -t 30`-drains the container while measuring:
//
//   1. every client receives `server_draining` before the socket closes
//      (or a clean close),
//   2. every op that was durable-acked before the drain is durable in
//      PostgreSQL (sent == acked == rows),
//   3. the container exits well before the stop timeout,
//   4. clients reconnect to a restarted instance and catch up (sync
//      returns the full history from the DB floor).
//
// Protocol flows mirror the proven harnesses: tests/realtime/e2e.test.ts
// (JWKS-file auth, makeOp canonical bytes, binary clientOps framing) and
// rust/sync-gateway/tests/lifecycle_integration.rs (the drain sequence).
//
// Prerequisites:
//   - docker compose db up (concord-db; host port 5433)
//   - the e2e JWKS + key at .agent/scratch/phase-3/ (generated by the
//     realtime suite's setup; regenerate via tests/realtime global setup
//     if missing)
//   - the release gateway image (docker/gateway.Dockerfile) — pass the
//     tag as $1 (default concord-gateway:smoke)
//
// Usage:
//   node scripts/release/drain-test.mjs [image-tag] [N]
//   node scripts/release/drain-test.mjs concord-gateway:smoke 10

import { readFileSync } from "node:fs";
import { createPrivateKey, createSign } from "node:crypto";
import { Client } from "pg";

const REPO = decodeURIComponent(new URL("../..", import.meta.url).pathname);
const DB_URL = "postgres://concord:concord_local_dev@127.0.0.1:5433/concord_test";
const ISSUER = "https://e2e.clerk.accounts.dev";
const JWKS_FILE = `${REPO}.agent/scratch/phase-3/e2e-jwks.json`;
const KEY_DER = `${REPO}.agent/scratch/phase-3/e2e-key.der`;
const HOST_PORT = 18795; // published port of the container's 8791

const IMAGE = process.argv[2] ?? "concord-gateway:smoke";
const N = Number(process.argv[3] ?? 10);

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// ---------------------------------------------------------------------------
// JWT signing (same construction as tests/realtime/e2e.test.ts).
// ---------------------------------------------------------------------------

function signToken(sub) {
  const der = readFileSync(KEY_DER);
  const key = createPrivateKey({ key: der, format: "der", type: "pkcs8" });
  const b64u = (b) => Buffer.from(b).toString("base64url");
  const now = Math.floor(Date.now() / 1000);
  const header = b64u(JSON.stringify({ alg: "RS256", typ: "JWT", kid: "e2e-key-1" }));
  const payload = b64u(JSON.stringify({ sub, iss: ISSUER, iat: now, exp: now + 600 }));
  const signature = createSign("RSA-SHA256").update(`${header}.${payload}`).sign(key).toString("base64url");
  return `${header}.${payload}.${signature}`;
}

// Canonical Phase 2 insert op (byte-for-byte the C++ serializer shape —
// same as the e2e harness makeOp).
function makeOp(replica, counter) {
  const op = Buffer.alloc(32);
  op[0] = 1; // version
  op[1] = 1; // type insert
  op.writeBigUInt64LE(replica, 2);
  op.writeBigUInt64LE(counter, 10);
  op.writeBigUInt64LE(1n, 18); // lamport
  op[26] = 0; // left anchor none
  op[27] = 0; // right anchor none
  op[28] = 1; // kind text
  op[29] = 1; // scalar len
  op[30] = 0x61; // 'a'
  op[31] = 0; // attr count
  return op;
}

// Binary clientOps frame (big-endian header, BATCH_KIND_CLIENT_OPS).
function clientOpsFrame(batchId, ops) {
  const payloadBytes = ops.reduce((s, o) => s + o.length + 4, 0);
  const out = Buffer.alloc(12 + payloadBytes);
  out[0] = 1; // wire version
  out[1] = 0x20; // BATCH_KIND_CLIENT_OPS
  out.writeBigUInt64BE(batchId, 2);
  out.writeUInt16BE(ops.length, 10);
  let offset = 12;
  for (const op of ops) {
    out.writeUInt32BE(op.length, offset);
    op.copy(out, offset + 4);
    offset += 4 + op.length;
  }
  return out;
}

// ---------------------------------------------------------------------------
// One client: handshake -> authenticate -> join -> keepalive writes.
// ---------------------------------------------------------------------------

class DrainClient {
  constructor(id, clerkId, documentId, replicaBase) {
    this.id = id;
    this.clerkId = clerkId;
    this.documentId = documentId;
    this.replica = replicaBase;
    this.counter = 0n;
    this.sentOps = [];
    this.ackedOps = [];
    this.sawDraining = false;
    this.sawDrainingBeforeClose = null;
    this.closeCode = null;
    this.closedAt = null;
    this.syncBatchOps = 0;
    this.syncDone = false;
    this.ready = false;
    this.ws = null;
    this.queue = [];
  }

  connect(port) {
    return new Promise((resolve, reject) => {
      this.ws = new WebSocket(`ws://127.0.0.1:${port}/api/v1/sync`);
      this.ws.binaryType = "arraybuffer";
      this.ws.onopen = () => {
        // Kick off the handshake (hello → authenticate → join → sync).
        this.ws.send(JSON.stringify({ v: 1, type: "hello", payload: { clientProtocolVersion: 1 } }));
        resolve();
      };
      this.ws.onerror = (e) => reject(new Error(`client ${this.id}: ws error ${e.message}`));
      this.ws.onclose = (ev) => {
        this.closeCode = ev.code;
        this.closedAt = Date.now();
        this.sawDrainingBeforeClose = this.sawDraining;
      };
      this.ws.onmessage = (ev) => this.onMessage(ev.data);
    });
  }

  onMessage(data) {
    if (typeof data === "string") {
      const frame = JSON.parse(data);
      switch (frame.type) {
        case "hello_ack":
          this.ws.send(JSON.stringify({ v: 1, type: "authenticate", payload: { token: signToken(this.clerkId) } }));
          break;
        case "authenticated":
          this.ws.send(
            JSON.stringify({
              v: 1,
              type: "join_document",
              payload: { documentId: this.documentId, stateSummary: [] },
            }),
          );
          break;
        case "join_accepted":
          // Request full history catch-up (cursor 0 = from the floor).
          this.ws.send(JSON.stringify({ v: 1, type: "sync_request", payload: { cursor: "0" } }));
          break;
        case "durable_ack":
          this.ackedOps.push(...frame.payload.opIds);
          break;
        case "server_draining":
          this.sawDraining = true;
          break;
        case "sync_done":
          this.syncDone = true;
          this.ready = true;
          break;
        default:
          break;
      }
    } else {
      // Binary sync batch (kind 0x21): [u64 nextCursor][u8 hasMore][u16 count]
      // — count sits at offset 11 (13-byte header), per src/lib/sync/protocol.ts
      // decodeDataFrame (BATCH_KIND_SYNC).
      const buf = Buffer.from(data);
      if (buf.length >= 13 && buf[0] === 1 && buf[1] === 0x21) {
        this.syncBatchOps += buf.readUInt16BE(11);
      }
    }
  }

  async writeOps(count) {
    const ops = [];
    const firstCounter = this.counter + 1n;
    for (let i = 0; i < count; i += 1) {
      this.counter += 1n;
      ops.push(makeOp(this.replica, this.counter));
      this.sentOps.push(`${this.replica}:${this.counter}`);
    }
    this.batchId = (this.batchId ?? 0n) + 1n;
    this.ws.send(clientOpsFrame(this.batchId, ops));
    // Wait until all just-sent op identities appear in ackedOps.
    const ids = new Set(ops.map((_, i) => `${this.replica}:${firstCounter + BigInt(i)}`));
    const deadline = Date.now() + 10_000;
    while (Date.now() < deadline) {
      const acked = new Set(this.ackedOps);
      if (ids.values().toArray().every((id) => acked.has(id))) return true;
      await sleep(50);
    }
    return false;
  }

  close() {
    try {
      this.ws.close();
    } catch {
      /* already closed */
    }
  }
}

async function main() {
  console.log(`=== P7-M017 container drain test — image=${IMAGE} N=${N} ===`);

  const sql = new Client({ connectionString: DB_URL });
  await sql.connect();

  // Self-heal: integration suites (and other agents in a shared dev DB)
  // recreate concord_test concurrently. If the gateway tables are missing,
  // re-apply BOTH migration families (drizzle first, then the gateway's
  // own run_migrations — which happens at gateway boot below). This also
  // documents the two-family rule: npm drizzle migrations are NOT enough.
  let gatewayReady = true;
  try {
    await sql.query("SELECT 1 FROM gateway_schema_migrations LIMIT 1");
  } catch {
    gatewayReady = false;
  }
  if (!gatewayReady) {
    console.log("gateway tables missing — applying drizzle migrations…");
    const { execFileSync } = await import("node:child_process");
    execFileSync("node", ["scripts/db/migrate.mjs", "--test"], { stdio: "inherit" });
    console.log("drizzle applied; gateway migrations run at container boot (run_migrations)");
  }

  // --- Start the gateway container FIRST: its boot run_migrations creates
  // the gateway tables when missing (the drizzle family must already be
  // applied — self-heal above). Seeding happens AFTER readiness so the
  // op-log table exists.
  const clerkId = `user_drain_${Date.now()}`;
  const containerName = "concord-drain-test";
  const { execFileSync } = await import("node:child_process");
  execFileSync("docker", ["rm", "-f", containerName], { stdio: "ignore" });
  execFileSync(
    "docker",
    [
      "run",
      "-d",
      "--name",
      containerName,
      "--add-host=host.docker.internal:host-gateway",
      "-e",
      "GATEWAY_BIND_HOST=0.0.0.0",
      "-e",
      "GATEWAY_BIND_PORT=8791",
      "-e",
      `GATEWAY_DATABASE_URL=postgres://concord:concord_local_dev@host.docker.internal:5433/concord_test`,
      "-e",
      `GATEWAY_CLERK_ISSUER=${ISSUER}`,
      "-e",
      `GATEWAY_JWKS_FILE=/etc/concord/jwks.json`,
      "-v",
      `${JWKS_FILE}:/etc/concord/jwks.json:ro`,
      "-p",
      `127.0.0.1:${HOST_PORT}:8791`,
      IMAGE,
    ],
    { stdio: "inherit" },
  );

  // Wait for readiness.
  let ready = false;
  for (let i = 0; i < 40 && !ready; i += 1) {
    try {
      const res = await fetch(`http://127.0.0.1:${HOST_PORT}/api/v1/health/ready`);
      ready = res.ok;
    } catch {
      /* retry */
    }
    if (!ready) await sleep(250);
  }
  if (!ready) {
    console.error("FAIL: gateway container never became ready");
    process.exit(1);
  }
  console.log("gateway container ready (health/ready OK)");

  // Seed one user + one document owned by that user.
  const user = (
    await sql.query("INSERT INTO users (clerk_user_id) VALUES ($1) RETURNING id", [clerkId])
  ).rows[0].id;
  const documentId = (
    await sql.query(
      "INSERT INTO documents (owner_user_id, title, initial_content) VALUES ($1, 'drain-test', '') RETURNING id",
      [user],
    )
  ).rows[0].id;
  await sql.query("DELETE FROM crdt_operations WHERE document_id = $1", [documentId]);
  console.log(`document ${documentId} (user ${clerkId})`);

  // --- Open N sessions, each with pending durable writes --------------------
  const clients = [];
  for (let i = 0; i < N; i += 1) {
    const c = new DrainClient(i, clerkId, documentId, 1_000_000n + BigInt(i * 1000));
    await c.connect(HOST_PORT);
    // Wait until the join+sync cycle completes (session is Ready — the
    // gateway's write gate: client_ops is invalid_state before sync_done).
    const deadline = Date.now() + 10_000;
    while (!c.ready && Date.now() < deadline) await sleep(50);
    if (!c.ready) {
      console.error(`FAIL: client ${i} never reached ready (gateway write gate)`);
      process.exit(1);
    }
    clients.push(c);
  }
  console.log(`${N} sessions connected + joined (all Ready)`);

  // Each client writes ops until durable-acked (in-flight durable state).
  let writesOk = true;
  for (const c of clients) {
    const ok = await c.writeOps(3);
    if (!ok) writesOk = false;
  }
  const sentTotal = clients.reduce((s, c) => s + c.sentOps.length, 0);
  const ackedTotal = clients.reduce((s, c) => s + c.ackedOps.length, 0);
  console.log(`pre-drain: sent=${sentTotal} acked=${ackedTotal} (all clients durable-acked: ${writesOk})`);

  // --- docker stop -t 30 while sessions are live ---------------------------
  const t0 = Date.now();
  try {
    execFileSync("docker", ["stop", "-t", "30", containerName], { encoding: "utf8", stdio: "ignore" });
  } catch (e) {
    console.error("docker stop failed:", e.message);
    process.exit(1);
  }
  const drainMs = Date.now() - t0;
  const exitCode = JSON.parse(
    execFileSync("docker", ["inspect", containerName, "--format", "{{json .State}}"], { encoding: "utf8" }),
  ).ExitCode;
  console.log(`docker stop -t 30 → container exited in ${drainMs} ms, exit code ${exitCode}`);

  // Drain notice accounting (each client's socket got the frame before
  // close — collect with a short settle window).
  await sleep(500);
  const drainNotices = clients.filter((c) => c.sawDraining).length;
  const cleanCloses = clients.filter((c) => c.closedAt !== null).length;
  console.log(
    `drain notices observed: ${drainNotices}/${N}; sockets closed: ${cleanCloses}/${N}` +
      `; close codes: ${[...new Set(clients.map((c) => c.closeCode))].join(",")}`,
  );

  // --- Durability check: every pre-drain ack is a durable row ---------------
  const rows = await sql.query("SELECT operation_id FROM crdt_operations WHERE document_id = $1", [
    documentId,
  ]);
  const durableIds = new Set(rows.rows.map((r) => r.operation_id));
  const ackedNotDurable = clients.flatMap((c) => c.ackedOps.filter((id) => !durableIds.has(id)));
  console.log(
    `durable rows: ${rows.rows.length}; acked-but-not-durable: ${ackedNotDurable.length}` +
      ` (sent=${sentTotal}, acked=${ackedTotal})`,
  );

  // --- Restart + reconnect + catch-up ----------------------------------------
  execFileSync("docker", ["rm", "-f", containerName], { stdio: "ignore" });
  execFileSync(
    "docker",
    [
      "run",
      "-d",
      "--name",
      containerName,
      "--add-host=host.docker.internal:host-gateway",
      "-e",
      "GATEWAY_BIND_HOST=0.0.0.0",
      "-e",
      "GATEWAY_BIND_PORT=8791",
      "-e",
      `GATEWAY_DATABASE_URL=postgres://concord:concord_local_dev@host.docker.internal:5433/concord_test`,
      "-e",
      `GATEWAY_CLERK_ISSUER=${ISSUER}`,
      "-e",
      `GATEWAY_JWKS_FILE=/etc/concord/jwks.json`,
      "-v",
      `${JWKS_FILE}:/etc/concord/jwks.json:ro`,
      "-p",
      `127.0.0.1:${HOST_PORT}:8791`,
      IMAGE,
    ],
    { stdio: "ignore" },
  );
  let restarted = false;
  for (let i = 0; i < 40 && !restarted; i += 1) {
    try {
      const res = await fetch(`http://127.0.0.1:${HOST_PORT}/api/v1/health/ready`);
      restarted = res.ok;
    } catch {
      /* retry */
    }
    if (!restarted) await sleep(250);
  }
  console.log(`restarted instance ready: ${restarted}`);

  // One FRESH client (empty state) joins and must catch up the full history.
  const catcher = new DrainClient(N, clerkId, documentId, 9_000_000n);
  await catcher.connect(HOST_PORT);
  const deadline = Date.now() + 15_000;
  while (Date.now() < deadline) {
    if (catcher.syncDone && catcher.syncBatchOps >= sentTotal) break;
    await sleep(100);
  }
  console.log(
    `catch-up after restart: sync_done=${catcher.syncDone}, ops replayed=${catcher.syncBatchOps}/${sentTotal}`,
  );

  // --- Verdict ---------------------------------------------------------------
  const pass =
    writesOk &&
    drainNotices === N &&
    ackedNotDurable.length === 0 &&
    exitCode === 0 &&
    drainMs < 30_000 &&
    restarted &&
    catcher.syncDone &&
    catcher.syncBatchOps >= sentTotal;

  clients.forEach((c) => c.close());
  catcher.close();
  execFileSync("docker", ["rm", "-f", containerName], { stdio: "ignore" });
  await sql.query("DELETE FROM crdt_operations WHERE document_id = $1", [documentId]);
  await sql.end();

  console.log(pass ? "DRAIN TEST: PASS" : "DRAIN TEST: FAIL");
  process.exit(pass ? 0 : 1);
}

main().catch((e) => {
  console.error("drain test error:", e);
  process.exit(1);
});
