import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

/**
 * Feature 8 — PWA artifact contract. These pin the installability inputs
 * AND the safety-critical service-worker cache rules (a wrong SW policy
 * would reintroduce the P7-M032 stale-engine bug or cache auth responses).
 */

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

describe("PWA manifest", () => {
  it("is valid JSON with installability essentials and existing icons", async () => {
    const raw = await readFile(path.join(repoRoot, "public/manifest.webmanifest"), "utf8");
    const manifest = JSON.parse(raw) as {
      name: string;
      start_url: string;
      scope: string;
      display: string;
      icons: Array<{ src: string; sizes: string; type: string; purpose: string }>;
    };
    expect(manifest.name).toBe("Concord");
    expect(manifest.start_url).toBe("/");
    expect(manifest.scope).toBe("/");
    expect(manifest.display).toBe("standalone");
    // Chromium installability requires a 192px+ PNG icon.
    const sizes = manifest.icons.map((icon) => icon.sizes);
    expect(sizes).toContain("192x192");
    expect(sizes).toContain("512x512");
    for (const icon of manifest.icons) {
      const bytes = await readFile(path.join(repoRoot, "public", icon.src.replace(/^\//, "")));
      // PNG magic bytes (generated by scripts/pwa/generate-icons.mjs).
      expect([...bytes.slice(0, 4)]).toEqual([0x89, 0x50, 0x4e, 0x47]);
      expect(icon.type).toBe("image/png");
    }
  });
});

describe("service worker cache policy", () => {
  const swSource = async () => readFile(path.join(repoRoot, "public/sw.js"), "utf8");

  it("never caches API or session traffic", async () => {
    const source = await swSource();
    expect(source).toContain('url.pathname.startsWith("/api/")');
    expect(source).toContain("request.method !== \"GET\"");
  });

  it("keeps engine assets network-first (P7-M032 staleness contract)", async () => {
    const source = await swSource();
    // /crdt-worker.js and /wasm/* must prefer the network; a cache-first
    // policy here would pin stale engine code across deploys.
    expect(source).toContain('url.pathname === "/crdt-worker.js"');
    expect(source).toContain('url.pathname.startsWith("/wasm/")');
    expect(source).toContain("networkFirst(request, STATIC_CACHE)");
    expect(source).not.toContain("cacheFirst(request, STATIC_CACHE))\n    return;\n  }\n  if (isEngineAsset");
  });

  it("intercepts only same-origin GET navigations and bounds the shell cache", async () => {
    const source = await swSource();
    expect(source).toContain("url.origin !== self.location.origin");
    expect(source).toContain('request.mode === "navigate"');
    expect(source).toContain("MAX_NAVIGATION_ENTRIES");
  });
});

describe("PWA registration gate", () => {
  it("registers only in production builds", async () => {
    const source = await readFile(
      path.join(repoRoot, "src/components/pwa-registration.tsx"),
      "utf8",
    );
    expect(source).toContain('process.env.NODE_ENV !== "production"');
  });
});
