// P2-M032/M033: native/WASM golden parity + runtime wrapper tests.
//
// The golden fixture (cpp/crdt/tests/golden/phase2.json) is generated by the
// NATIVE engine (tests/golden_gen.cpp) and contains the serialized ops plus
// the expected visible JSON and digest. The WASM engine must reproduce both
// byte-for-byte — browser and native share one semantic core (DEC-023).
import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
    ConcordEngine,
    SUPPORTED_PROTOCOL_VERSION,
} from "@/lib/crdt/runtime";
import type { ConcordModule } from "@/lib/crdt/wasm-types";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const wasmDist = path.join(repoRoot, "wasm/dist");

interface GoldenFixture {
    ops: string[];
    visible: string;
    digest: string;
}

async function loadFactory() {
    const source = await readFile(path.join(wasmDist, "concord-crdt.js"), "utf8");
    const binary = await readFile(path.join(wasmDist, "concord-crdt.wasm"));
    // The generated glue is an ES/CJS-ambiguous script; evaluate the factory
    // and provide instantiation explicitly (glue no longer supports
    // Module.wasmBinary).
    const load = new Function(`${source}; return loadConcordCrdt;`)();
    return (await load({
        instantiateWasm(
            info: WebAssembly.Imports,
            receiveInstance: (instance: WebAssembly.Instance) => void,
        ) {
            WebAssembly.instantiate(binary, info).then((result) =>
                receiveInstance(result.instance),
            );
            return {};
        },
    })) as ConcordModule;
}

describe("native/WASM golden parity", () => {
    it("replays the native golden fixture with identical visible JSON and digest", async () => {
        const fixture = JSON.parse(
            await readFile(path.join(repoRoot, "cpp/crdt/tests/golden/phase2.json"), "utf8"),
        ) as GoldenFixture;

        const engine = await ConcordEngine.create(999n, loadFactory);
        try {
            for (const hex of fixture.ops) {
                const bytes = Uint8Array.from(
                    hex.match(/.{2}/g)!.map((byte) => parseInt(byte, 16)),
                );
                const result = engine.applyRemote(bytes);
                expect(result === "applied" || result === "duplicate").toBe(true);
            }
            expect(JSON.parse(engine.visibleJson())).toEqual(fixture.visible);
            expect(engine.digest()).toBe(fixture.digest);
        } finally {
            engine.free();
        }
    });
});

describe("runtime wrapper", () => {
    it("creates an empty engine and round-trips a local edit", async () => {
        const engine = await ConcordEngine.create(7n, loadFactory);
        try {
            expect(engine.streamSize()).toBe(0);
            const op = engine.localInsertText(0, 0x68); // 'h'
            expect(op.length).toBeGreaterThan(0);
            // Own op replayed is a duplicate (already integrated locally).
            expect(engine.applyRemote(op)).toBe("duplicate");
            expect(engine.streamSize()).toBe(1);
            expect(engine.visibleJson()).toContain('"t":"h"');
            expect(engine.digest()).toMatch(/^sha256:[0-9a-f]{64}$/);
        } finally {
            engine.free();
        }
    });

    it("rejects malformed remote frames with structured errors", async () => {
        const engine = await ConcordEngine.create(7n, loadFactory);
        try {
            expect(() => engine.applyRemote(new Uint8Array([1, 2, 3]))).toThrow(/Malformed|apply_remote/);
        } finally {
            engine.free();
        }
    });

    it("round-trips snapshots through export/import and keeps the digest", async () => {
        const engine = await ConcordEngine.create(7n, loadFactory);
        try {
            engine.localInsertText(0, 0x61); // 'a'
            engine.localInsertText(1, 0x62); // 'b'
            engine.localSetAttr(0, "bold", "1");
            const snapshot = engine.exportSnapshot();
            expect(snapshot.length).toBeGreaterThan(0);

            const restored = await ConcordEngine.importFromSnapshot(9n, snapshot, loadFactory);
            try {
                expect(restored.visibleJson()).toBe(engine.visibleJson());
                expect(restored.digest()).toBe(engine.digest());
                // The restored engine can continue editing.
                restored.localInsertText(restored.streamSize(), 0x63); // 'c'
                expect(restored.streamSize()).toBe(3);
            } finally {
                restored.free();
            }
        } finally {
            engine.free();
        }
    });

    it("keeps protocol version constant aligned with the core", () => {
        expect(SUPPORTED_PROTOCOL_VERSION).toBe(1);
    });
});
